version: '2'

networks:
  basic:

services:
  jaeger:
    hostname: jaeger
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411      
    ports:
      - 6831:6831/udp
      - 16696:16686
      - 14268:14268
      - 9411:9411
    networks:
      - basic
  
  greeter:
    restart: always
    container_name: greeter
    hostname: greeter
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    image:
      gattal/istio-me
    environment:
      JAEGER_SERVICE_NAME: 'greeter01'
      # JAEGER_AGENT_HOST: jaeger
      # JAEGER_AGENT_PORT: 6831      
      JAEGER_SAMPLER_PARAM: '1'
      JAEGER_REPORTER_LOG_SPANS: 'true'
      JAEGER_SAMPLER_TYPE: const
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    ports: 
      - 9080:9080
    depends_on:      
      - timer
      - jaeger
    #entrypoint: "/app/istio-me"
    command: greet 
    networks: 
      - basic
  
  timer:
    restart: always
    container_name: timer
    hostname: timer
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    image:
      gattal/istio-me
    environment: 
      JAEGER_SERVICE_NAME: 'timer01'
      # JAEGER_AGENT_HOST: jaeger
      # JAEGER_AGENT_PORT: 6831
      JAEGER_REPORTER_LOG_SPANS: 'true'
      JAEGER_SAMPLER_PARAM: '1'
      JAEGER_SAMPLER_TYPE: const
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    ports: 
      - 8080:8080
    depends_on:      
      - jaeger
    #entrypoint: "/app/istio-me"
    command: time 
    networks: 
      - basic