// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greeter.proto

package trials

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRq) Reset()         { *m = HelloRq{} }
func (m *HelloRq) String() string { return proto.CompactTextString(m) }
func (*HelloRq) ProtoMessage()    {}
func (*HelloRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{0}
}

func (m *HelloRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRq.Unmarshal(m, b)
}
func (m *HelloRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRq.Marshal(b, m, deterministic)
}
func (m *HelloRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRq.Merge(m, src)
}
func (m *HelloRq) XXX_Size() int {
	return xxx_messageInfo_HelloRq.Size(m)
}
func (m *HelloRq) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRq.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRq proto.InternalMessageInfo

func (m *HelloRq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloRs struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRs) Reset()         { *m = HelloRs{} }
func (m *HelloRs) String() string { return proto.CompactTextString(m) }
func (*HelloRs) ProtoMessage()    {}
func (*HelloRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{1}
}

func (m *HelloRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRs.Unmarshal(m, b)
}
func (m *HelloRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRs.Marshal(b, m, deterministic)
}
func (m *HelloRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRs.Merge(m, src)
}
func (m *HelloRs) XXX_Size() int {
	return xxx_messageInfo_HelloRs.Size(m)
}
func (m *HelloRs) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRs.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRs proto.InternalMessageInfo

func (m *HelloRs) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRq)(nil), "trials.HelloRq")
	proto.RegisterType((*HelloRs)(nil), "trials.HelloRs")
}

func init() { proto.RegisterFile("greeter.proto", fileDescriptor_e585294ab3f34af5) }

var fileDescriptor_e585294ab3f34af5 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x3f, 0x4e, 0xc3, 0x30,
	0x14, 0x87, 0x95, 0x16, 0x5a, 0x61, 0x54, 0x51, 0x79, 0xa1, 0x0a, 0x20, 0x55, 0x99, 0xf8, 0xd3,
	0xe4, 0xd1, 0xb2, 0x75, 0xa2, 0x30, 0x94, 0x89, 0xa1, 0x6c, 0x6c, 0x6e, 0xb1, 0x1c, 0x83, 0xe3,
	0x67, 0x6c, 0x53, 0x06, 0xc4, 0xc2, 0x11, 0xe0, 0x3e, 0x5c, 0x82, 0x2b, 0x70, 0x00, 0x8e, 0x80,
	0xe2, 0x84, 0x85, 0x0e, 0x88, 0xc9, 0x4f, 0xdf, 0xfb, 0xe4, 0xf7, 0xfc, 0x33, 0xe9, 0x08, 0xcb,
	0xb9, 0xe7, 0x36, 0x33, 0x16, 0x3d, 0xd2, 0x96, 0xb7, 0x92, 0x29, 0x17, 0xef, 0x0a, 0x44, 0xa1,
	0x38, 0x30, 0x23, 0x81, 0x69, 0x8d, 0x9e, 0x79, 0x89, 0xda, 0x55, 0x56, 0x3c, 0x08, 0xc7, 0x22,
	0x15, 0x5c, 0xa7, 0xee, 0x91, 0x09, 0xc1, 0x2d, 0xa0, 0x09, 0xc6, 0xaa, 0x9d, 0xec, 0x91, 0xf6,
	0x05, 0x57, 0x0a, 0x67, 0xf7, 0x94, 0x92, 0x35, 0xcd, 0x0a, 0xde, 0x8b, 0xfa, 0xd1, 0xfe, 0xc6,
	0x2c, 0xd4, 0xc9, 0xce, 0x4f, 0xdb, 0xd1, 0x2e, 0x69, 0x16, 0x4e, 0xd4, 0xdd, 0xb2, 0x1c, 0x5d,
	0x92, 0xf6, 0xb4, 0x5a, 0x90, 0x9e, 0x93, 0xf5, 0xe0, 0xd1, 0xad, 0xac, 0x5a, 0x32, 0xab, 0x6f,
	0x8d, 0x7f, 0x01, 0x97, 0xf4, 0x5e, 0x3e, 0x3e, 0xdf, 0x1a, 0x94, 0x76, 0x61, 0x39, 0x84, 0xbc,
	0x84, 0xf0, 0x54, 0xce, 0x7a, 0x3e, 0xfb, 0x8a, 0x5e, 0x27, 0xef, 0x11, 0x15, 0x64, 0xb3, 0x7e,
	0x77, 0x9f, 0x19, 0x99, 0x5c, 0x91, 0xce, 0x14, 0x97, 0x52, 0xdf, 0xb0, 0xfe, 0xc4, 0x7b, 0xa6,
	0xe8, 0x41, 0xee, 0xbd, 0x71, 0x63, 0x00, 0x21, 0x7d, 0xfe, 0x30, 0xcf, 0x16, 0x58, 0x80, 0xa8,
	0x8c, 0x94, 0x95, 0x06, 0x48, 0xe7, 0x25, 0xa6, 0x05, 0x8f, 0xb7, 0x6b, 0x9e, 0x05, 0x7e, 0x2a,
	0x0a, 0x26, 0x55, 0xe9, 0x8f, 0x9a, 0xc3, 0xec, 0xf8, 0xb0, 0x11, 0x35, 0x46, 0x5d, 0x66, 0x8c,
	0x92, 0x8b, 0x90, 0x09, 0xdc, 0x3a, 0xd4, 0xe3, 0x15, 0x62, 0x8f, 0xfe, 0x31, 0xf2, 0x7a, 0xf0,
	0xa7, 0x02, 0xe6, 0x4e, 0x40, 0x15, 0xca, 0xbc, 0x15, 0x7e, 0xe1, 0xe4, 0x3b, 0x00, 0x00, 0xff,
	0xff, 0xf4, 0x2a, 0xeb, 0x20, 0xea, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	Hello(ctx context.Context, in *HelloRq, opts ...grpc.CallOption) (*HelloRs, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) Hello(ctx context.Context, in *HelloRq, opts ...grpc.CallOption) (*HelloRs, error) {
	out := new(HelloRs)
	err := c.cc.Invoke(ctx, "/trials.Greeter/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	Hello(context.Context, *HelloRq) (*HelloRs, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trials.Greeter/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).Hello(ctx, req.(*HelloRq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "trials.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Greeter_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greeter.proto",
}
