// Code generated by protoc-gen-go. DO NOT EDIT.
// source: timer.proto

package trials

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TimeRs struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeRs) Reset()         { *m = TimeRs{} }
func (m *TimeRs) String() string { return proto.CompactTextString(m) }
func (*TimeRs) ProtoMessage()    {}
func (*TimeRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad0307ee16b652d2, []int{0}
}

func (m *TimeRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeRs.Unmarshal(m, b)
}
func (m *TimeRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeRs.Marshal(b, m, deterministic)
}
func (m *TimeRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeRs.Merge(m, src)
}
func (m *TimeRs) XXX_Size() int {
	return xxx_messageInfo_TimeRs.Size(m)
}
func (m *TimeRs) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeRs.DiscardUnknown(m)
}

var xxx_messageInfo_TimeRs proto.InternalMessageInfo

func (m *TimeRs) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*TimeRs)(nil), "trials.TimeRs")
}

func init() { proto.RegisterFile("timer.proto", fileDescriptor_ad0307ee16b652d2) }

var fileDescriptor_ad0307ee16b652d2 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0xcd, 0x3f, 0xcb, 0xc2, 0x30,
	0x10, 0x06, 0x70, 0xca, 0xfb, 0x5a, 0x30, 0x82, 0x48, 0x06, 0x91, 0xba, 0x88, 0x93, 0x83, 0xbd,
	0x80, 0x0e, 0xee, 0x82, 0x5f, 0xa0, 0x38, 0xb9, 0xa5, 0x1a, 0xe3, 0x61, 0xe3, 0x85, 0xe4, 0x2a,
	0xf8, 0xed, 0x25, 0x0d, 0x6e, 0x0f, 0xf7, 0xe7, 0xf7, 0x88, 0x09, 0xa3, 0x33, 0x01, 0x7c, 0x20,
	0x26, 0x59, 0x72, 0x40, 0xdd, 0xc5, 0x6a, 0x69, 0x89, 0x6c, 0x67, 0xd4, 0x30, 0x6d, 0xfb, 0xbb,
	0x32, 0xce, 0xf3, 0x27, 0x1f, 0xad, 0x2b, 0x51, 0x9e, 0xd1, 0x99, 0x26, 0xca, 0x99, 0xf8, 0x73,
	0xd1, 0x2e, 0x8a, 0x55, 0xb1, 0x19, 0x37, 0x29, 0xee, 0x0e, 0x62, 0x94, 0x76, 0x41, 0x82, 0xf8,
	0x4f, 0x41, 0xce, 0x21, 0x53, 0xf0, 0xa3, 0xe0, 0x94, 0xa8, 0x6a, 0x0a, 0xb9, 0x0a, 0x32, 0x75,
	0x84, 0xcb, 0xd6, 0x22, 0x3f, 0xfa, 0x16, 0xae, 0xe4, 0x94, 0xa5, 0x37, 0xbe, 0x6e, 0xba, 0xd6,
	0xcc, 0xba, 0x53, 0x18, 0x19, 0xa9, 0x76, 0x46, 0xf9, 0xa7, 0x55, 0xf9, 0xad, 0x2d, 0x07, 0x6f,
	0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x99, 0xf2, 0x1b, 0xf2, 0xbf, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TimerClient is the client API for Timer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TimerClient interface {
	Time(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*TimeRs, error)
}

type timerClient struct {
	cc *grpc.ClientConn
}

func NewTimerClient(cc *grpc.ClientConn) TimerClient {
	return &timerClient{cc}
}

func (c *timerClient) Time(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*TimeRs, error) {
	out := new(TimeRs)
	err := c.cc.Invoke(ctx, "/trials.Timer/Time", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimerServer is the server API for Timer service.
type TimerServer interface {
	Time(context.Context, *empty.Empty) (*TimeRs, error)
}

func RegisterTimerServer(s *grpc.Server, srv TimerServer) {
	s.RegisterService(&_Timer_serviceDesc, srv)
}

func _Timer_Time_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimerServer).Time(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trials.Timer/Time",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimerServer).Time(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Timer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "trials.Timer",
	HandlerType: (*TimerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Time",
			Handler:    _Timer_Time_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "timer.proto",
}
